#!/bin/bash
AS=../riscv32-unknown-elf-as
OBJCOPY=../riscv32-unknown-elf-objcopy

fname=$1
if [[ ${fname: -2} != ".s" ]]
then
	echo "Usage: assembler FILE"
	echo "FILE: must have .s extension"
	exit
fi

AS_OUTPUT="${fname%.s}.o"
OBJCOPY_OUTPUT="${fname%.s}.bin"
${AS} $fname -o ${AS_OUTPUT}
${OBJCOPY} -O binary -j .text ${AS_OUTPUT} ${OBJCOPY_OUTPUT}
