#!/bin/bash
if type riscv32-unknown-elf-as > /dev/null 2>&1
then
    AS=riscv32-unknown-elf-as
elif [[ -e ../riscv32-unknown-elf-as ]]
then
    AS=../riscv32-unknown-elf-as
else
    echo "No riscv as found!"
    exit 1
fi
if type riscv32-unknown-elf-objcopy > /dev/null 2>&1
then
    OBJCOPY=riscv32-unknown-elf-objcopy
elif [[ -e ../riscv32-unknown-elf-objcopy ]]
then
    OBJCOPY=../riscv32-unknown-elf-objcopy
else
    echo "No riscv objcopy found!"
    exit 1
fi

fname=$1
if [[ ${fname: -2} != ".s" ]]
then
	echo "Usage: assembler FILE"
	echo "FILE: must have .s extension"
	exit
fi

AS_OUTPUT="${fname%.s}.o"
OBJCOPY_OUTPUT="${fname%.s}.bin"
${AS} $fname -o ${AS_OUTPUT}
${OBJCOPY} -O binary -j .text ${AS_OUTPUT} ${OBJCOPY_OUTPUT}
